### ISSUE TITLE
Sync fails with Unauthorized 401 message

### ISSUE THREAD

**Issue by tenninebt** [dustin/gopro#11]
The app worked fine but after a few hours, the sync command is failing. I'm getting and Unauthorized 401 message.
I thought it might be a token generated during the authentication expired so I tried reauth command, auth to start over but none of them fixed it. I'm wondering if they updated the API or revoked the Api Key you are using.
Did you face the same issue before? Could it be a DDos protection mechanism? 
It feels like it is Cloudfront that is blocking me, but I can't figure out why?

**Comment by dustin** [comment]
There's no automatic reauthentication.  Try `gopro reauth`

Automating this is a bit less trivial than one would think.
