### ISSUE TITLE
Unexpected MediumType: "MultiClipEdit" while performing first sync

### ISSUE THREAD

**Issue by fabiocatalao** [dustin/gopro#14]
I've installed it in a Raspberry, and I'm trying to run it for the first time.

I've performed the auth steps and now I'm trying to run the sync command for the first time and it's failing with the following error:

```
$ gopro sync -v
D: Reading auth token from DB
gopro: JSONError "Error in $.type: Unexpected MediumType: \"MultiClipEdit\""
```

The same error happens when trying to run fetchall.

It's a type of Media that was created using GoPro app and was available in the GoPro Media Library, filtering by Edits. I've already deleted it from there but it still fails.

Please let me know if there are additional ways to debug the issue.

**Comment by dustin** [comment]
Oh neat.  That's easy to fix.  I'll check to see if there are more medium types added recently and roll them all out.

**Comment by fabiocatalao** [comment]
It's now syncing. Thank you!
