### ISSUE TITLE
Integrate with GoProX

### ISSUE THREAD

**Issue by fxstein** [dustin/gopro#17]
Hi,

Would love to integrate with [GoProX](https://github.com/fxstein/GoProX) workflow.

Primarily to upload processed media to GoPro Plus. What would be the most lightweight way to make this happen (CLI only)?

Very much appreciate what you are doing!

**Comment by dustin** [comment]
This particular tool was primarily created to give me a bit of assurance that I won't lose data if something happens to GoPro cloud, so most of the tooling is around managing stuff you keep there.  But it does have some decent upload (and download) functionality.

`gopro upload` will do a lot of it (assuming it's run from a directory that has a `gopro.db` that you've authenticated with the service from).

It's going to default to uploading media it can recognize as camera media (i.e., original filenames), but if you want to hand-assemble media, you can use `gopro createmulti` to specify the medium type and sequence of parts that should make it up.

I also realized there are a couple of web-only features that might be useful to expose to the CLI, such as generating kml from uploaded media.

**Comment by dustin** [comment]
I don't think there's anything to do in this project for this.  Integrations have gotten easier and there's a FUSE filesystem to access all of your media without having to download it (but also, you can download it across multiple computers if you like).

**Comment by fxstein** [comment]
Thanks for the followup!
