### ISSUE TITLE
GoPro Max files are not supported

### ISSUE THREAD

**Issue by mkueh** [dustin/gopro#22]
Hi, 

I want to sync my GoPro Max files with this program, but I get the following error. 

I: Ignoring some unknown files: ["GS010128.1.360"]
I: Have 0 media items to upload in 0 parts with a total of 0 chunks (0 MB)

**Comment by dustin** [comment]
Oh neat.  I don't have one of these to classify, so I haven't tried.  I'll look into that.

I've had a few files before, so I should be able to look into their rough shape.  If you have a small clip you can share, that might help as well.

**Comment by mkueh** [comment]
Sure, I would like to help more too, but my Haskell is not really good xD

[https://drive.google.com/file/d/18KLFg9ocgYisMeCqesh12EctIlhL52xh/view?usp=sharing](url)

If you download the file, can you give me a small message, than I can remove it :)

**Comment by dustin** [comment]
I think I did this according to spec.  The linked file appeared to be the second chapter in a multi-chaptered 360 file.  Apparently you can't have that many chapters, but I went ahead and considered the leading 0 part of the ID since I'm doing that in other ones anyway.
