### ISSUE TITLE
Web app with 'gopro serve' does not work

### ISSUE THREAD

**Issue by Alvaro-sdl** [dustin/gopro#25]
Hello! I started using your tool since I found it very useful, and trying to make it work. 

When I use 'gopro serve', the web server starts but going to 'localhost:8008' only brings up 'Something went wrong' and the console displays 'static/index.html: withBinaryFile: does not exist (No such file or directory)'. 

Do you know if it is a setup issue or a bug?

**Comment by dustin** [comment]
You'll need the `static` directory from the source tree available.  You can either run it from the same directory, or you can pass `--static /path/to/static` to tell it where the web content is kept.

It's not exactly a bug, but it isn't a great user experience.

**Comment by Alvaro-sdl** [comment]
Aaah I see. Now it seems to work. 

At first I didn't quite understand the static bit.

Thank you very much!

**Comment by rhorer** [comment]
I'm finding that it doesn't work unless I start `gopro serve` from within the/a directory that contains the `static` directory. Putting the path in `config.toml` or in a `--static` statement on the command line doesn't work for me.

**Comment by michaellammers** [comment]
> I'm finding that it doesn't work unless I start `gopro serve` from within the/a directory that contains the `static` directory. Putting the path in `config.toml` or in a `--static` statement on the command line doesn't work for me.

I have the same experience

**Comment by dustin** [comment]
Oh weird.  That does seem to be the case.  I apparently broke this at some point in the past and managed to never notice.  I'll get a fix out soon.

**Comment by dustin** [comment]
This works for me now:  `gopro -v --static ~/prog/gopro/static serve`

**Comment by dustin** [comment]
(also tested toml)

It was a dumb issue.  Sorry for the inconvenience.

**Comment by michaellammers** [comment]
Thanks for the great work and prompt action Dustin! 👌
