### ISSUE TITLE
Sqlite database keeps record of a media even after deleting it via GoPro Cloud official web interface

### ISSUE THREAD

**Issue by Alvaro-sdl** [dustin/gopro#26]
I found a file I didn't want to keep in the GoPro Cloud official web interface. Therefore, I deleted it. Even after using 'gopro sync', I realised the database still keeps record of it. 

I tried using 'gopro reprocess', even though it is not made for deletions (just in case), and it didn't fix it. 

Firstly, is it somehow marked as deleted? Or is it a bug? Or maybe the tool is just simply thought to be always used with the custom web interface?

Secondly, do you think just dropping the record from the media table would work to fix it?

P.S. Thanks for publishing your amazing tool!!

**Comment by dustin** [comment]
I made a `removedeleted` command that deals with this.  I had five of them in my own DB.  It takes a few minutes to get the ~8k records from gopro for mine, but does what I expected.
