### ISSUE TITLE
GoPro Serve Error - I was unable to load the media: bad body: Problem with the value at json[30]['file_size']:

### ISSUE THREAD

**Issue by hubsngu** [dustin/gopro#29]
```
I was unable to load the media: bad body: Problem with the value at json[30]['file_size']:

    null

Expecting an INT
```

<img width="838" alt="image" src="https://github.com/dustin/gopro/assets/145893158/5b7b7209-05e0-419f-b6d6-69a22c08b0a6">

Likely caused by me hitting ^C during `gopro sync` and then retrying. I've tried to run gopro fetchall with no luck.

**Comment by dustin** [comment]
Hmm...  File size _is_ optional, but I'm not sure what would lead to know knowing what it is.

I've updated the UI to allow for a missing size.  That should get it rendering and you can always refresh the one that doesn't know its size.
