### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by LushS-io** [dustin/gopro#31]
Received the following error that would halt sync from continuing.

`gopro: SQLite3 returned ErrorError while attempting to perform prepare "insert into files (media_id, section, label, type, item_number, file_size) values (?, ?, ?, ?, ?)": 5 values for 6 columns.`

I was able to get it running by simply adding an additional arg (?)

**Comment by dustin** [comment]
Ugh.  Sorry about that.  I've been using postgres and apparently am lacking a test.
