### ISSUE TITLE
JSONError Unexpected MediumType Audio

### ISSUE THREAD

**Issue by LushS-io** [dustin/gopro#35]
While running `gopro sync` I received the following error.
`JSONError "Error in $.type: Unexpected MediumType: \"Audio\""`

I found that issue #14 was another Unexpected MediumType that was easily resolved.

I see that the error is thrown in dep pkg here: https://github.com/dustin/gopro-plus/blob/master/src/GoPro/Plus/Media.hs#L115 although I don't believe a distinctive `Audio` MediumType would fall into the photo "bucket".

I recently did make a GoPro edit on mobile using a local soundfile so I'm supposing this is what's being seen all of a sudden.

**Comment by dustin** [comment]
Wow, that is unexpected.  I've updated the list a few times from the enum I've found.

Thanks for the callout on it being more than just adding that constructor.  Still not quite sure what that means.  heh

**Comment by dustin** [comment]
Audio seems to be the only new type.  I added support for it in gopro-plus and the gopro package will use this now.  I have no idea how to actually get one of these things to even know what to do with it.  We'll scan it for GPMF, I guess.  I don't know how to upload it or anything.

I might be able to get one by recording with a media mod or something, but that doesn't make much sense either.

**Comment by LushS-io** [comment]
cool, I'll see if I can repro another if it works out, thanks for the quick update and responsiveness!
