### ISSUE TITLE
failed to parse field 'extra-deps' when installing

### ISSUE THREAD

**Issue by worjak** [dustin/gopro#36]
I get this: 
`jaw@wormnethub:~/gopro$ sudo stack install
Could not parse '/home/jaw/gopro/stack.yaml':
Aeson exception:
Error in $['extra-deps'][1]: failed to parse field 'extra-deps': (Invalid package identifier: "crypton-0.33@sha256:5e92f29b9b7104d91fcdda1dec9400c9ad1f1791c231cc41ceebd783fb517dee,18202","crypton-0.33@sha256:5e92f29b9b7104d91fcdda1dec9400c9ad1f1791c231cc41ceebd783fb517dee,18202")
See http://docs.haskellstack.org/en/stable/yaml_configuration/
`
What to do? I'm on ubuntu 18.04 LTS

**Comment by dustin** [comment]
I'd definitely not recommend doing this stuff as root, but that's probably not related to your problem.

I assume you're not using nix?  It's possible you have an old version of stack or old package libs or something.  What does `stack --version` say?

**Comment by worjak** [comment]
It says "Version 1.5.1 i386"

**Comment by worjak** [comment]
So I get that nix is a package manager like apt-get - will Nix solve my problem? Thanks for your time!

**Comment by dustin** [comment]
That's a very old version of stack.  I think that's the issue.

nix is a package manager that's part of nixos.  I use it on MacOS X, but all of my Linux machines are running nixos so I've not tried it on anything else.

The primary thing it does is make sure that people have the right versions of the necessary software when installing things.  e.g., correct postgres libs, build tools, compiler versions, etc...  This project has three different subprojects in three different languages and I don't like keeping track of all that stuff, so my installs are all automatic via `cd`.  Same stuff we use at work.

Asking people to install that sort of thing is kind of a big deal, but you'll at least need a recent version of the various tools.  You might try [ghcup](https://www.haskell.org/ghcup/) to install the Haskell toolkit (including stack and compilers).  I've not actually tried it, though.

**Comment by worjak** [comment]
Thanks for the advice. What version of stack will be sufficient? I’d prefer to stay with Ubuntu but will consider to upgrade to a more recent release.
