### ISSUE TITLE
Error after refresh web

### ISSUE THREAD

**Issue by jpbusman** [dustin/gopro#8]
**I was unable to load the media: bad body: Problem with the value at json[3].height:

    null

Expecting an INT**

When syncing the first time the web showed some content, but after a while a refresh gives this message (got a couple of 100 items from 3119)
Is there a corrupt image in the gopro cloud, how can I find the one causing this problem of fix this?

**Comment by jpbusman** [comment]
> **I was unable to load the media: bad body: Problem with the value at json[3].height:
> 
> ```
> null
> ```
> 
> Expecting an INT**
> 
> When syncing the first time the web showed some content, but after a while a refresh gives this message (got a couple of 100 items from 3119) Is there a corrupt image in the gopro cloud, how can I find the one causing this problem of fix this?

Found the entries in the sqlite db by a json select and deleted the problem files in the db and the cloud, now it works fine

**Comment by dustin** [comment]
Oh neat, I just got one of these.  It appears to be a `MultiClipEdit` the service made from uploaded media.  This gives me a chance to make a workaround in any case.
