### ISSUE TITLE
Unsupported Parser

### ISSUE THREAD

**Issue by synchrotron** [dustin/gopro#9]
Would really like an alternative to the unworkable GoPro App and I'm more than comfortable with CLI, but I don't know any Haskell so I'm stumped by this error.

Having followed the install instructions, have authenticated and running the first 'gopro sync' it worked it's way though more the 200 of the 244 items and now I get

`gopro -v sync`
`D: Reading auth token from DB`
`I: 0 new items`
`I: Fetching meta 0`
`D: Need meta: []`
`I: Updating ("o6Ra0w75aMqnV",GPMF)`
`gopro: unsupported parser: 'S'`
`CallStack (from HasCallStack):`
`  error, called at src/GoPro/GPMF.hs:129:20 in gpmf-0.1.0.3-350fHnVuGmDJDL1tyyYPbe:GoPro.GPMF`

If you're able to shed any light on this so I can complete the sync that would be appreciated.

Thanks for sharing these tools

**Comment by synchrotron** [comment]
Can confirm the update to use latest GPMF parse seems to have worked and my sync is now successful.

**Comment by dustin** [comment]
Thanks!
